# Meta Data for SEO

## Homepage
title = "Consumet"
titleSeparator = "-"
titleAddition = "The Official Consumet Website"
description = "The Official Website for Consumet, an API that procides information and links to various entertainment."

## Documentation
docsVersion = "0.1"

## Open Graph
images = []
ogLocale = "en_US"
domainTLD = "consumet.org"
titleHome = "Consumet"

## Twitter Cards
twitterSite = "ConsumetOrg"
twitterCreator = "ConsumetOrg"

## JSON-LD
schemaType = "Organization"
schemaName = "Cousumet"
schemaLocale = "en-US"
## TODO
## schemaLogo = ""
## schemaLogoWidth = 512
## schemaLogoHeight = 512
## schemaImage = ""
## schemaImageWidth = 1280
## schemaImageHeight = 640
schemaTwitter = "https://twitter.com/consumetorg"
## schemaLinkedIn = ""
schemaGitHub = "https://github.com/consumet"
## schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

## TODO
# Images
## quality = 85
## bgColor = "#fff"
## landscapePhotoWidths = [900, 800, 700, 600, 500]
## portraitPhotoWidths = [800, 700, 600, 500]
## lqipWidth = "20x"
## smallLimit = "300"

# Footer
footer = "Powered by <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.netlify.com\">Netlify</a>, <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://gohugo.io/\">Hugo</a>, and <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022-2023 Consumet"

# Alert
alert = false
alertDismissable = false
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/consumet/website"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
